const router = require('express').Router();

const tasks = require('../../mock data/tasks.json');

router.get('/', (req,res) =>{
    res.json(tasks);
});

// POST /tasks
router.post('/', (req, res) => {
    const { body } = req;

    // when we have a data store ours id will be generated by Mongo DB
    // for now mock id generation
    const id = tasks.length + 1;
    
    res.json({ ...body, id });
});

router.get('/:id', (req, res) => {
    const { params } = req;
    const id = params.id;

    // find a quiz by its id
    // when we have a database we will query this from Mongo
    const task = tasks.find((task) => {
        return task.id === parseInt(id);
    });

    if (task) {
        res.json(task);
    } else {
       res.status(404).json({ error: `task by id ${id} not found.` });
    }
});

router.put('/:id', (req, res) => {
    const { id } = req.params;
    const {name, details, timeline} = req.body;

    const task = tasks.find((task) => {
        return task.id === parseInt(id);
    });

    if(task){
        if(task.status === 'assigned'){
            const taskupdated = {...task, name, details, timeline};
            res.json(taskupdated);
        }else{
            res.status(400).json({error : 'only assigned tasks can be updated '});
        }
    }else{
        res.status(404).json({error: 'Could not find task'});
    }
    
});

// Delete

router.delete('/:id', (req, res) => {
    const { params } = req;
    const id = params.id;

    const task = tasks.find((task) => {
        return task.id === parseInt(id);
    });
   


    if (task) {
        res.json({ deleted: { name: task.name, id: task.id } });
        }else {
        res.status(404).json({ error: `Task by id ${id} not found.` });
    }
});

module.exports = router;